/* CompiladorAula.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorAula.java */
package parser;

import recovery.*;
import view.Tela;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileWriter;
import java.io.Reader;
import java.io.StringReader;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import controleDeArquivos.CreateFile;

public class CompiladorAula/*@bgen(jjtree)*/implements CompiladorAulaTreeConstants, CompiladorAulaConstants {/*@bgen(jjtree)*/
  protected static JJTCompiladorAulaState jjtree = new JJTCompiladorAulaState();
    // janela principal da aplicação
    static final Tela window = new Tela();

    // controle global de erro para o modo pânico
    static Token lastError = null;
    static boolean eof = false;

        static boolean parserInitialized = false;

        private static void initParser(Reader r) {
    if (!parserInitialized) {
        // primeira vez: pode chamar o construtor
        new CompiladorAula(r);
        parserInitialized = true;
    } else {
        // nas próximas vezes: só ReInit
        CompiladorAula.ReInit(r);
    }
}
    // ===================== MAIN: abre a interface =====================
    public static void main(String[] args) {
        // mostra a janela
        window.setVisible(true);

        // botão "Compilar" chama inicia()
                window.getCompilar().addActionListener(
    new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            // limpa console + árvore
            window.setVazioConsoleMsg();
            // chama o compilador
            inicia();
        }
    });
    }

    // ===================== INICIA A COMPILAÇÃO =====================
static void inicia() {
    // pega o código digitado na interface
    String codigo = window.getTextArquivo().getText();

    // limpa console + árvore sintática
    window.setVazioConsoleMsg();

    // ======================================================
    // 1) LISTA OS TOKENS RECONHECIDOS
    // ======================================================

    // inicializa o parser para essa entrada
    Reader tokensReader = new StringReader(codigo);
    initParser(tokensReader);   // usa new só da primeira vez, depois ReInit

    try {
        window.setConsole("TOKENS RECONHECIDOS:\n");

        Token t;
        while (true) {
            // usa o scanner do próprio parser
            t = CompiladorAula.getNextToken();
            if (t.kind == EOF) {
                break;
            }

            window.setConsole(
                "Linha " + t.beginLine +
                ", Coluna " + t.beginColumn +
                "  ->  " + tokenImage[t.kind].replace("\"", "") +
                "  [" + t.image + "]\n"
            );
        }
    } catch (TokenMgrError e) {
        window.setConsole("\nErro l\u00e9xico durante listagem de tokens: "
                          + e.getMessage() + "\n");
    }

    // ======================================================
    // 2) RODA A ANÁLISE SINTÁTICA (modo pânico + árvore)
    // ======================================================

    // re-inicializa o parser com o mesmo código para a parte sintática
    Reader parseReader = new StringReader(codigo);
    CompiladorAula.ReInit(parseReader);

    // reseta flags globais para o modo pânico
    lastError = null;
    eof = false;

    try {
        // chama o símbolo inicial da gramática (seu main da linguagem)
        SimpleNode raiz = CompiladorAula.main();
        // desenha árvore sintática na área "Arvore Sintática"
        ArvoreSintatica.dump(raiz, "->", window);
    }
    catch (ParseException e) {
        // se ainda escapou algum erro sintático, mostra aqui
        window.setConsole("\nErro sint\u00e1tico n\u00e3o recuperado: "
                          + e.getMessage() + "\n");
    }
    catch (TokenMgrError e) {
        window.setConsole("\nErro l\u00e9xico durante an\u00e1lise: "
                          + e.getMessage() + "\n");
    }
    catch (Exception e) {
        window.setConsole("\nErro inesperado: " + e.getClass().getSimpleName()
                          + " - " + e.getMessage() + "\n");
    }


}



    // ===================== FUNÇÃO AUXILIAR im() =====================
    static public String im(int x) {
        int k;
        String s = tokenImage[x];
        k = s.lastIndexOf("\"");
        try {
            s = s.substring(1, k);
        } catch (StringIndexOutOfBoundsException e) {
        }
        return s;
    }

    // ===================== RECUPERAÇÃO EM MODO PÂNICO =====================
    static void consumeUntil(RecoverySet g,
                             ParseException e,
                             String met)
            throws ParseEOFException, ParseException {

        Token tok;

        System.out.println();
        window.setConsole("\n\n*** " + met + " ***");
        window.setConsole("\n     Conjunto de sincroniza\u00e7\u00e3o: " + g);

        if (g == null) {
            throw e;
        }

        tok = getToken(1); // token corrente

        while (!eof) {
            if (g.contains(tok.kind)) {
                window.setConsole("\n     Encontrado token de sincroniza\u00e7\u00e3o: " + im(tok.kind));
                break;
            }

            window.setConsole("\n     Ignorando o token: " + im(tok.kind));
            getNextToken();
            tok = getToken(1);

            if (tok.kind == EOF && !g.contains(EOF)) {
                eof = true;
            }
        }

        if (tok != lastError) {
            System.out.println(e.getMessage());
            window.setConsole("\n" + e.getMessage());
            lastError = tok;
        }

        if (eof) {
            throw new ParseEOFException("Encontrei EOF onde n\u00e3o deveria.");
        }
    }

/* ---------------------------------------------------- START BLOCO PRINCIPAL ---------------------------------------------------------------------------------*/
  static final public SimpleNode main() throws ParseException {/*@bgen(jjtree) main */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.main;
    try {
      try {
        CREATEWORLD();
        ID();
        PONTOVIRGULA();
        bloco();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "main");
      }
jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
}

  static final public void bloco() throws ParseException {/*@bgen(jjtree) bloco */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.bloco;
    try {
      try {
        OVERWORLD();
        label_1:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:{
            ;
            break;
            }
          default:
            jj_la1[0] = jj_gen;
            break label_1;
          }
          declaracaoVariavel();
        }
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[1] = jj_gen;
            break label_2;
          }
          comando();
        }
        BEDROCK();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "bloco");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END BLOCO PRINCIPAL ---------------------------------------------------------------------------------*/
  static final public 
void comando() throws ParseException {/*@bgen(jjtree) comando */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMANDO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.comando;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID:{
          atribuicao();
          break;
          }
        case IF:{
          ifStmt();
          break;
          }
        case WHILE:{
          whileLoop();
          break;
          }
        case FOR:{
          forLoop();
          break;
          }
        case BREAK:{
          breakStmt();
          break;
          }
        case PRINTF:{
          printStmt();
          break;
          }
        case CONTINUE:{
          continueStmt();
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "comando");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- START BLOCO WHILE ---------------------------------------------------------------------------------*/
  static final public void whileLoop() throws ParseException {/*@bgen(jjtree) whileLoop */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILELOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.whileLoop;
    try {
      try {
        WHILE();
        expressao();
        ABRIRWHILE();
        blocoWhile();
        FECHARWHILE();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "whileLoop");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void blocoWhile() throws ParseException {/*@bgen(jjtree) blocoWhile */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCOWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.blocoWhile;
    try {
      try {
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:{
            declaracaoVariavel();
            break;
            }
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            comando();
            break;
            }
          default:
            jj_la1[3] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[4] = jj_gen;
            break label_3;
          }
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "blocoWhile");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void breakStmt() throws ParseException {/*@bgen(jjtree) breakStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTBREAKSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.breakStmt;
    try {
      try {
        BREAK();
        PONTOVIRGULA();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "breakStmt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END BLOCO WHILE ---------------------------------------------------------------------------------*/
  static final public 
void continueStmt() throws ParseException {/*@bgen(jjtree) continueStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTCONTINUESTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.continueStmt;
    try {
      try {
        CONTINUE();
        PONTOVIRGULA();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "continueStmt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- START BLOCO FOR ---------------------------------------------------------------------------------*/
  static final public void forLoop() throws ParseException {/*@bgen(jjtree) forLoop */
  SimpleNode jjtn000 = new SimpleNode(JJTFORLOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.forLoop;
    try {
      try {
        FOR();
        PARENTES_ESQUERDA();
        forInitOpt();
        PONTOVIRGULA();
        forCondOpt();
        PONTOVIRGULA();
        forUpdateOpt();
        PARENTES_DIREITA();
        ABRIRFOR();
        blocoFor();
        FECHARFOR();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "forLoop");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void blocoFor() throws ParseException {/*@bgen(jjtree) blocoFor */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCOFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.blocoFor;
    try {
      try {
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:{
            declaracaoVariavel();
            break;
            }
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            comando();
            break;
            }
          default:
            jj_la1[5] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            break label_4;
          }
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "blocoFor");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void forInitOpt() throws ParseException {/*@bgen(jjtree) forInitOpt */
  SimpleNode jjtn000 = new SimpleNode(JJTFORINITOPT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.forInitOpt;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPOINTEIRO:
        case TIPOFLUTUANTE:
        case TIPOTEXTO:
        case TIPOBINARIO:
        case ID:{
          forInit();
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "forInitOpt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void forCondOpt() throws ParseException {/*@bgen(jjtree) forCondOpt */
  SimpleNode jjtn000 = new SimpleNode(JJTFORCONDOPT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.forCondOpt;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TRUE:
        case FALSE:
        case NOT:
        case DECIMAL:
        case ID:
        case STRING:
        case PARENTES_ESQUERDA:{
          expressao();
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "forCondOpt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void forUpdateOpt() throws ParseException {/*@bgen(jjtree) forUpdateOpt */
  SimpleNode jjtn000 = new SimpleNode(JJTFORUPDATEOPT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.forUpdateOpt;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID:{
          atribuicaoFor();
          label_5:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case VIRGULA:{
              ;
              break;
              }
            default:
              jj_la1[9] = jj_gen;
              break label_5;
            }
            VIRGULA();
            atribuicaoFor();
          }
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "forUpdateOpt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void forInit() throws ParseException {/*@bgen(jjtree) forInit */
  SimpleNode jjtn000 = new SimpleNode(JJTFORINIT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.forInit;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPOINTEIRO:
        case TIPOFLUTUANTE:
        case TIPOTEXTO:
        case TIPOBINARIO:{
          tipoDado();
          listaDeclaracoes();
          break;
          }
        case ID:{
          atribuicaoFor();
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "forInit");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void atribuicaoFor() throws ParseException {/*@bgen(jjtree) atribuicaoFor */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAOFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.atribuicaoFor;
    try {
      try {
        ID();
        ATRIBUICAO();
        expressao();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "atribuicaoFor");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END BLOCO FOR ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- START ESTRUTURA DE CONTROLE ---------------------------------------------------------------------------------*/
  static final public void ifStmt() throws ParseException {/*@bgen(jjtree) ifStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTIFSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.ifStmt;
    try {
      try {
        IF();
        expressao();
        ABRIRIF();
        THEN();
        blocoIf();
        FECHARIF();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELSE:{
          elseClause();
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "ifStmt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void elseClause() throws ParseException {/*@bgen(jjtree) elseClause */
  SimpleNode jjtn000 = new SimpleNode(JJTELSECLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.elseClause;
    try {
      try {
        ELSE();
        ABRIRELSE();
        blocoElse();
        FECHARELSE();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "elseClause");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void blocoIf() throws ParseException {/*@bgen(jjtree) blocoIf */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCOIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.blocoIf;
    try {
      try {
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:{
            declaracaoVariavel();
            break;
            }
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            comando();
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[14] = jj_gen;
            break label_6;
          }
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "blocoIf");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void blocoElse() throws ParseException {/*@bgen(jjtree) blocoElse */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOCOELSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.blocoElse;
    try {
      try {
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:{
            declaracaoVariavel();
            break;
            }
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            comando();
            break;
            }
          default:
            jj_la1[15] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TIPOINTEIRO:
          case TIPOFLUTUANTE:
          case TIPOTEXTO:
          case TIPOBINARIO:
          case IF:
          case PRINTF:
          case CONTINUE:
          case WHILE:
          case BREAK:
          case FOR:
          case ID:{
            ;
            break;
            }
          default:
            jj_la1[16] = jj_gen;
            break label_7;
          }
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "blocoElse");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END ESTRUTURA DE CONTROLE ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- START ATRIBUIÇÃO ---------------------------------------------------------------------------------*/
  static final public void atribuicao() throws ParseException {/*@bgen(jjtree) atribuicao */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.atribuicao;
    try {
      try {
        ID();
        ATRIBUICAO();
        expressao();
        PONTOVIRGULA();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "atribuicao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END ATRIBUIÇÃO ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- START PRINTF ---------------------------------------------------------------------------------*/
  static final public void printStmt() throws ParseException {/*@bgen(jjtree) printStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTPRINTSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.printStmt;
    try {
      try {
        PRINTF();
        PARENTES_ESQUERDA();
        STRING();
        PARENTES_DIREITA();
        PONTOVIRGULA();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "printStmt");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END PRINTF ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- START EXPRESSOES (LL(1)) ------------------------------*/

// Expressão completa (nível mais alto: OR)
  static final public void expressao() throws ParseException {/*@bgen(jjtree) expressao */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.expressao;
    try {
      try {
        exprOr();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "expressao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprOr -> exprAnd (OR exprAnd)*
  static final public void exprOr() throws ParseException {/*@bgen(jjtree) exprOr */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPROR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprOr;
    try {
      try {
        exprAnd();
        exprOrLinha();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprOr");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exprOrLinha() throws ParseException {/*@bgen(jjtree) exprOrLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRORLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprOrLinha;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OR:{
          OR();
          exprAnd();
          exprOrLinha();
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprOrLinha");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprAnd -> exprRel (AND exprRel)*
  static final public void exprAnd() throws ParseException {/*@bgen(jjtree) exprAnd */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprAnd;
    try {
      try {
        exprRel();
        exprAndLinha();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprAnd");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exprAndLinha() throws ParseException {/*@bgen(jjtree) exprAndLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRANDLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprAndLinha;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:{
          AND();
          exprRel();
          exprAndLinha();
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprAndLinha");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprRel -> exprAditiva (RelOp exprAditiva)?
  static final public void exprRel() throws ParseException {/*@bgen(jjtree) exprRel */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRREL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprRel;
    try {
      try {
        exprAditiva();
        exprRelLinha();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprRel");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exprRelLinha() throws ParseException {/*@bgen(jjtree) exprRelLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRRELLINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprRelLinha;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MAIOR:
        case MENOR:
        case MENOR_IGUAL:
        case MAIOR_IGUAL:
        case DIFERENTE:
        case IGUAL:{
          tipoCondicao();
          exprAditiva();
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprRelLinha");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprAditiva -> exprMultiplicativa ( (+|-) exprMultiplicativa )*
  static final public void exprAditiva() throws ParseException {/*@bgen(jjtree) exprAditiva */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRADITIVA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprAditiva;
    try {
      try {
        exprMultiplicativa();
        exprAditivaLinha();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprAditiva");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exprAditivaLinha() throws ParseException {/*@bgen(jjtree) exprAditivaLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRADITIVALINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprAditivaLinha;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SOMA:
        case SUBTRACAO:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case SOMA:{
            SOMA();
            break;
            }
          case SUBTRACAO:{
            SUBTRACAO();
            break;
            }
          default:
            jj_la1[20] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          exprMultiplicativa();
          exprAditivaLinha();
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprAditivaLinha");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprMultiplicativa -> exprUnaria ( (*|/) exprUnaria )*
  static final public void exprMultiplicativa() throws ParseException {/*@bgen(jjtree) exprMultiplicativa */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRMULTIPLICATIVA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprMultiplicativa;
    try {
      try {
        exprUnaria();
        exprMultiplicativaLinha();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprMultiplicativa");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exprMultiplicativaLinha() throws ParseException {/*@bgen(jjtree) exprMultiplicativaLinha */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRMULTIPLICATIVALINHA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprMultiplicativaLinha;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MULTIPLICACAO:
        case DIVISAO:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MULTIPLICACAO:{
            MULTIPLICACAO();
            break;
            }
          case DIVISAO:{
            DIVISAO();
            break;
            }
          default:
            jj_la1[22] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          exprUnaria();
          exprMultiplicativaLinha();
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprMultiplicativaLinha");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// exprUnaria -> NOT exprUnaria | primária
  static final public void exprUnaria() throws ParseException {/*@bgen(jjtree) exprUnaria */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRUNARIA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprUnaria;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NOT:{
          NOT();
          exprUnaria();
          break;
          }
        case TRUE:
        case FALSE:
        case DECIMAL:
        case ID:
        case STRING:
        case PARENTES_ESQUERDA:{
          exprPrimaria();
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprUnaria");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// primária -> ID | DECIMAL | STRING | TRUE | FALSE | ( expressao )
  static final public void exprPrimaria() throws ParseException {/*@bgen(jjtree) exprPrimaria */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRPRIMARIA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.exprPrimaria;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID:{
          ID();
          break;
          }
        case DECIMAL:{
          DECIMAL();
          break;
          }
        case STRING:{
          STRING();
          break;
          }
        case TRUE:{
          TRUE();
          break;
          }
        case FALSE:{
          FALSE();
          break;
          }
        case PARENTES_ESQUERDA:{
          PARENTES_ESQUERDA();
          expressao();
          PARENTES_DIREITA();
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "exprPrimaria");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END EXPRESSOES (LL(1)) --------------------------------*/



/* ---------------------------------------------------- START DECLARACAO VARIAVEL ---------------------------------------------------------------------------------*/
  static final public 
void declaracaoVariavel() throws ParseException {/*@bgen(jjtree) declaracaoVariavel */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARACAOVARIAVEL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.declaracaoVariavel;
    try {
      try {
        tipoDado();
        listaDeclaracoes();
        PONTOVIRGULA();
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "declaracaoVariavel");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void listaDeclaracoes() throws ParseException {/*@bgen(jjtree) listaDeclaracoes */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTADECLARACOES);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.listaDeclaracoes;
    try {
      try {
        declaracaoUnica();
        label_8:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VIRGULA:{
            ;
            break;
            }
          default:
            jj_la1[26] = jj_gen;
            break label_8;
          }
          VIRGULA();
          declaracaoUnica();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "listaDeclaracoes");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void declaracaoUnica() throws ParseException {/*@bgen(jjtree) declaracaoUnica */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARACAOUNICA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.declaracaoUnica;
    try {
      try {
        ID();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ATRIBUICAO:{
          ATRIBUICAO();
          expressao();
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          ;
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "declaracaoUnica");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END DECLARACAO VARIAVEL ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- START TIPOS DE DADOS---------------------------------------------------------------------------------*/
  static final public 
void tipoDado() throws ParseException {/*@bgen(jjtree) tipoDado */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPODADO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.tipoDado;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPOINTEIRO:{
          TIPOINTEIRO();
          break;
          }
        case TIPOBINARIO:{
          TIPOBINARIO();
          break;
          }
        case TIPOTEXTO:{
          TIPOTEXTO();
          break;
          }
        case TIPOFLUTUANTE:{
          TIPOFLUTUANTE();
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "tipoDado");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- END TIPOS DE DADOS ---------------------------------------------------------------------------------*/

/* ---------------------------------------------------- STAR TIPO DE CONDIÇÃO ---------------------------------------------------------------------------------*/
  static final public 
void tipoCondicao() throws ParseException {/*@bgen(jjtree) tipoCondicao */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOCONDICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);RecoverySet sincronizacao = First.tipoCondicao;
    try {
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MAIOR:{
          MAIOR();
          break;
          }
        case MENOR:{
          MENOR();
          break;
          }
        case MAIOR_IGUAL:{
          MAIOR_IGUAL();
          break;
          }
        case MENOR_IGUAL:{
          MENOR_IGUAL();
          break;
          }
        case IGUAL:{
          IGUAL();
          break;
          }
        case DIFERENTE:{
          DIFERENTE();
          break;
          }
        default:
          jj_la1[29] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (ParseException e) {
consumeUntil(sincronizacao, e, "tipoCondicao");
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* ---------------------------------------------------- STAR TIPO DE CONDIÇÃO ---------------------------------------------------------------------------------*/

/* -------------------- FOLHAS DA ÁRVORE (TOKENS COMO NÃO TERMINAIS) -------------------- */

/* -------------------- NÃO TERMINAIS PARA CADA TOKEN -------------------- */

/* PALAVRAS RESERVADAS */
  static final public 
void CREATEWORLD() throws ParseException {/*@bgen(jjtree) CREATEWORLD */
  SimpleNode jjtn000 = new SimpleNode(JJTCREATEWORLD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(CREATEWORLD);
    } finally {
if (jjtc000) {
                              jjtree.closeNodeScope(jjtn000, true);
                            }
    }
}

  static final public void OVERWORLD() throws ParseException {/*@bgen(jjtree) OVERWORLD */
  SimpleNode jjtn000 = new SimpleNode(JJTOVERWORLD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OVERWORLD);
    } finally {
if (jjtc000) {
                             jjtree.closeNodeScope(jjtn000, true);
                           }
    }
}

  static final public void BEDROCK() throws ParseException {/*@bgen(jjtree) BEDROCK */
  SimpleNode jjtn000 = new SimpleNode(JJTBEDROCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BEDROCK);
    } finally {
if (jjtc000) {
                             jjtree.closeNodeScope(jjtn000, true);
                           }
    }
}

  static final public void TIPOINTEIRO() throws ParseException {/*@bgen(jjtree) TIPOINTEIRO */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOINTEIRO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TIPOINTEIRO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// pedra
  static final public void TIPOFLUTUANTE() throws ParseException {/*@bgen(jjtree) TIPOFLUTUANTE */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOFLUTUANTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TIPOFLUTUANTE);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// agua
  static final public void TIPOTEXTO() throws ParseException {/*@bgen(jjtree) TIPOTEXTO */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOTEXTO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TIPOTEXTO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// placa
  static final public void TIPOBINARIO() throws ParseException {/*@bgen(jjtree) TIPOBINARIO */
  SimpleNode jjtn000 = new SimpleNode(JJTTIPOBINARIO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TIPOBINARIO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// redstone
  static final public 
void IF() throws ParseException {/*@bgen(jjtree) IF */
  SimpleNode jjtn000 = new SimpleNode(JJTIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// vinicius13
  static final public void THEN() throws ParseException {/*@bgen(jjtree) THEN */
  SimpleNode jjtn000 = new SimpleNode(JJTTHEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(THEN);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// build
  static final public void ELSE() throws ParseException {/*@bgen(jjtree) ELSE */
  SimpleNode jjtn000 = new SimpleNode(JJTELSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ELSE);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// monark
  static final public 
void TRUE() throws ParseException {/*@bgen(jjtree) TRUE */
  SimpleNode jjtn000 = new SimpleNode(JJTTRUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TRUE);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// tocha_acessa
  static final public void FALSE() throws ParseException {/*@bgen(jjtree) FALSE */
  SimpleNode jjtn000 = new SimpleNode(JJTFALSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FALSE);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// tocha_apagada
  static final public 
void PRINTF() throws ParseException {/*@bgen(jjtree) PRINTF */
  SimpleNode jjtn000 = new SimpleNode(JJTPRINTF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PRINTF);
    } finally {
if (jjtc000) {
                           jjtree.closeNodeScope(jjtn000, true);
                         }
    }
}

// chat
  static final public void CONTINUE() throws ParseException {/*@bgen(jjtree) CONTINUE */
  SimpleNode jjtn000 = new SimpleNode(JJTCONTINUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(CONTINUE);
    } finally {
if (jjtc000) {
                           jjtree.closeNodeScope(jjtn000, true);
                         }
    }
}

// isolaaados
  static final public 
void AND() throws ParseException {/*@bgen(jjtree) AND */
  SimpleNode jjtn000 = new SimpleNode(JJTAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(AND);
    } finally {
if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
}

// repetidor
  static final public void OR() throws ParseException {/*@bgen(jjtree) OR */
  SimpleNode jjtn000 = new SimpleNode(JJTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OR);
    } finally {
if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
}

// or
  static final public void NOT() throws ParseException {/*@bgen(jjtree) NOT */
  SimpleNode jjtn000 = new SimpleNode(JJTNOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NOT);
    } finally {
if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
}

// tocha_invertida
  static final public 
void ABRIRELSE() throws ParseException {/*@bgen(jjtree) ABRIRELSE */
  SimpleNode jjtn000 = new SimpleNode(JJTABRIRELSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ABRIRELSE);
    } finally {
if (jjtc000) {
                             jjtree.closeNodeScope(jjtn000, true);
                           }
    }
}

// acordaaaa_gente
  static final public void FECHARELSE() throws ParseException {/*@bgen(jjtree) FECHARELSE */
  SimpleNode jjtn000 = new SimpleNode(JJTFECHARELSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FECHARELSE);
    } finally {
if (jjtc000) {
                             jjtree.closeNodeScope(jjtn000, true);
                           }
    }
}

// ja_tamo_na_ditadura
  static final public 
void ABRIRIF() throws ParseException {/*@bgen(jjtree) ABRIRIF */
  SimpleNode jjtn000 = new SimpleNode(JJTABRIRIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ABRIRIF);
    } finally {
if (jjtc000) {
                           jjtree.closeNodeScope(jjtn000, true);
                         }
    }
}

// gamemode_creative
  static final public void FECHARIF() throws ParseException {/*@bgen(jjtree) FECHARIF */
  SimpleNode jjtn000 = new SimpleNode(JJTFECHARIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FECHARIF);
    } finally {
if (jjtc000) {
                           jjtree.closeNodeScope(jjtn000, true);
                         }
    }
}

// gamemode_survival
  static final public 
void WHILE() throws ParseException {/*@bgen(jjtree) WHILE */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
    } finally {
if (jjtc000) {
                              jjtree.closeNodeScope(jjtn000, true);
                            }
    }
}

// em_busca_da_casa_automatica
  static final public void ABRIRWHILE() throws ParseException {/*@bgen(jjtree) ABRIRWHILE */
  SimpleNode jjtn000 = new SimpleNode(JJTABRIRWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ABRIRWHILE);
    } finally {
if (jjtc000) {
                              jjtree.closeNodeScope(jjtn000, true);
                            }
    }
}

// farm_de_ferro
  static final public void FECHARWHILE() throws ParseException {/*@bgen(jjtree) FECHARWHILE */
  SimpleNode jjtn000 = new SimpleNode(JJTFECHARWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FECHARWHILE);
    } finally {
if (jjtc000) {
                              jjtree.closeNodeScope(jjtn000, true);
                            }
    }
}

// farm_de_cana_de_acucar
  static final public 
void BREAK() throws ParseException {/*@bgen(jjtree) BREAK */
  SimpleNode jjtn000 = new SimpleNode(JJTBREAK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BREAK);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

// kill
  static final public 
void FOR() throws ParseException {/*@bgen(jjtree) FOR */
  SimpleNode jjtn000 = new SimpleNode(JJTFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FOR);
    } finally {
if (jjtc000) {
                            jjtree.closeNodeScope(jjtn000, true);
                          }
    }
}

// intro_do_venom_extreme
  static final public void ABRIRFOR() throws ParseException {/*@bgen(jjtree) ABRIRFOR */
  SimpleNode jjtn000 = new SimpleNode(JJTABRIRFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ABRIRFOR);
    } finally {
if (jjtc000) {
                            jjtree.closeNodeScope(jjtn000, true);
                          }
    }
}

// portal_do_aether
  static final public void FECHARFOR() throws ParseException {/*@bgen(jjtree) FECHARFOR */
  SimpleNode jjtn000 = new SimpleNode(JJTFECHARFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FECHARFOR);
    } finally {
if (jjtc000) {
                            jjtree.closeNodeScope(jjtn000, true);
                          }
    }
}

// portal_do_nether


/* OPERADORES */
  static final public 
void SOMA() throws ParseException {/*@bgen(jjtree) SOMA */
  SimpleNode jjtn000 = new SimpleNode(JJTSOMA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SOMA);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// combine
  static final public void SUBTRACAO() throws ParseException {/*@bgen(jjtree) SUBTRACAO */
  SimpleNode jjtn000 = new SimpleNode(JJTSUBTRACAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SUBTRACAO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// -
  static final public void MULTIPLICACAO() throws ParseException {/*@bgen(jjtree) MULTIPLICACAO */
  SimpleNode jjtn000 = new SimpleNode(JJTMULTIPLICACAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MULTIPLICACAO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// *
  static final public void DIVISAO() throws ParseException {/*@bgen(jjtree) DIVISAO */
  SimpleNode jjtn000 = new SimpleNode(JJTDIVISAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DIVISAO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// /
  static final public void ATRIBUICAO() throws ParseException {/*@bgen(jjtree) ATRIBUICAO */
  SimpleNode jjtn000 = new SimpleNode(JJTATRIBUICAO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ATRIBUICAO);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// <-
  static final public void MAIOR() throws ParseException {/*@bgen(jjtree) MAIOR */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MAIOR);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// stronger
  static final public void MENOR() throws ParseException {/*@bgen(jjtree) MENOR */
  SimpleNode jjtn000 = new SimpleNode(JJTMENOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MENOR);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// weaker
  static final public void MENOR_IGUAL() throws ParseException {/*@bgen(jjtree) MENOR_IGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTMENOR_IGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MENOR_IGUAL);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// <=
  static final public void MAIOR_IGUAL() throws ParseException {/*@bgen(jjtree) MAIOR_IGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTMAIOR_IGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MAIOR_IGUAL);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// >=
  static final public void DIFERENTE() throws ParseException {/*@bgen(jjtree) DIFERENTE */
  SimpleNode jjtn000 = new SimpleNode(JJTDIFERENTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DIFERENTE);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// <>
  static final public void IGUAL() throws ParseException {/*@bgen(jjtree) IGUAL */
  SimpleNode jjtn000 = new SimpleNode(JJTIGUAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IGUAL);
    } finally {
if (jjtc000) {
                                jjtree.closeNodeScope(jjtn000, true);
                              }
    }
}

// =


/* OUTROS TOKENS LÉXICOS */
  static final public 
void DECIMAL() throws ParseException {/*@bgen(jjtree) DECIMAL */
  SimpleNode jjtn000 = new SimpleNode(JJTDECIMAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DECIMAL);
    } finally {
if (jjtc000) {
                          jjtree.closeNodeScope(jjtn000, true);
                        }
    }
}

  static final public void DIGITO() throws ParseException {/*@bgen(jjtree) DIGITO */
  SimpleNode jjtn000 = new SimpleNode(JJTDIGITO);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DIGITO);
    } finally {
if (jjtc000) {
                          jjtree.closeNodeScope(jjtn000, true);
                        }
    }
}

  static final public void ID() throws ParseException {/*@bgen(jjtree) ID */
  SimpleNode jjtn000 = new SimpleNode(JJTID);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ID);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

  static final public void LETRA() throws ParseException {/*@bgen(jjtree) LETRA */
  SimpleNode jjtn000 = new SimpleNode(JJTLETRA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LETRA);
    } finally {
if (jjtc000) {
                        jjtree.closeNodeScope(jjtn000, true);
                      }
    }
}

  static final public void PONTOVIRGULA() throws ParseException {/*@bgen(jjtree) PONTOVIRGULA */
  SimpleNode jjtn000 = new SimpleNode(JJTPONTOVIRGULA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PONTOVIRGULA);
    } finally {
if (jjtc000) {
                               jjtree.closeNodeScope(jjtn000, true);
                             }
    }
}

// ;
  static final public void VIRGULA() throws ParseException {/*@bgen(jjtree) VIRGULA */
  SimpleNode jjtn000 = new SimpleNode(JJTVIRGULA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VIRGULA);
    } finally {
if (jjtc000) {
                               jjtree.closeNodeScope(jjtn000, true);
                             }
    }
}

// ,
  static final public 
void STRING() throws ParseException {/*@bgen(jjtree) STRING */
  SimpleNode jjtn000 = new SimpleNode(JJTSTRING);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(STRING);
    } finally {
if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
}

// '...'
  static final public 
void PARENTES_ESQUERDA() throws ParseException {/*@bgen(jjtree) PARENTES_ESQUERDA */
  SimpleNode jjtn000 = new SimpleNode(JJTPARENTES_ESQUERDA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PARENTES_ESQUERDA);
    } finally {
if (jjtc000) {
                                    jjtree.closeNodeScope(jjtn000, true);
                                  }
    }
}

// (
  static final public void PARENTES_DIREITA() throws ParseException {/*@bgen(jjtree) PARENTES_DIREITA */
  SimpleNode jjtn000 = new SimpleNode(JJTPARENTES_DIREITA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PARENTES_DIREITA);
    } finally {
if (jjtc000) {
                                    jjtree.closeNodeScope(jjtn000, true);
                                  }
    }
}

// )
  static final public 
void DELIMITAR_VARCHAR() throws ParseException {/*@bgen(jjtree) DELIMITAR_VARCHAR */
  SimpleNode jjtn000 = new SimpleNode(JJTDELIMITAR_VARCHAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DELIMITAR_VARCHAR);
    } finally {
if (jjtc000) {
                                    jjtree.closeNodeScope(jjtn000, true);
                                  }
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorAulaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[30];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xf00,0x64061000,0x64061000,0x64061f00,0x64061f00,0x64061f00,0x64061f00,0xf00,0x218000,0x0,0x0,0xf00,0x4000,0x64061f00,0x64061f00,0x64061f00,0x64061f00,0x100000,0x80000,0x0,0x0,0x0,0x0,0x0,0x218000,0x18000,0x0,0x0,0xf00,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x4000,0x4000,0x4000,0x4000,0x4000,0x4000,0x4000,0xc5000,0x20000,0x4000,0x4000,0x0,0x4000,0x4000,0x4000,0x4000,0x0,0x0,0xfc0,0x6,0x6,0x18,0x18,0xc5000,0xc5000,0x20000,0x20,0x0,0xfc0,};
	}

  /** Constructor with InputStream. */
  public CompiladorAula(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CompiladorAula(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CompiladorAulaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CompiladorAula(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CompiladorAulaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CompiladorAulaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CompiladorAula(CompiladorAulaTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorAulaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 30; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[54];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 30; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 54; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
