/* Generated By:JavaCC: Do not edit this line. CompiladorAulaTreeConstants.java Version 7.0.12 */
package parser;

public interface CompiladorAulaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTBLOCO = 1;
  public int JJTCOMANDO = 2;
  public int JJTWHILELOOP = 3;
  public int JJTBLOCOWHILE = 4;
  public int JJTBREAKSTMT = 5;
  public int JJTCONTINUESTMT = 6;
  public int JJTFORLOOP = 7;
  public int JJTBLOCOFOR = 8;
  public int JJTFORINITOPT = 9;
  public int JJTFORCONDOPT = 10;
  public int JJTFORUPDATEOPT = 11;
  public int JJTFORINIT = 12;
  public int JJTATRIBUICAOFOR = 13;
  public int JJTIFSTMT = 14;
  public int JJTELSECLAUSE = 15;
  public int JJTBLOCOIF = 16;
  public int JJTBLOCOELSE = 17;
  public int JJTATRIBUICAO = 18;
  public int JJTPRINTSTMT = 19;
  public int JJTEXPRESSAO = 20;
  public int JJTEXPROR = 21;
  public int JJTEXPRORLINHA = 22;
  public int JJTEXPRAND = 23;
  public int JJTEXPRANDLINHA = 24;
  public int JJTEXPRREL = 25;
  public int JJTEXPRRELLINHA = 26;
  public int JJTEXPRADITIVA = 27;
  public int JJTEXPRADITIVALINHA = 28;
  public int JJTEXPRMULTIPLICATIVA = 29;
  public int JJTEXPRMULTIPLICATIVALINHA = 30;
  public int JJTEXPRUNARIA = 31;
  public int JJTEXPRPRIMARIA = 32;
  public int JJTDECLARACAOVARIAVEL = 33;
  public int JJTLISTADECLARACOES = 34;
  public int JJTDECLARACAOUNICA = 35;
  public int JJTTIPODADO = 36;
  public int JJTTIPOCONDICAO = 37;
  public int JJTCREATEWORLD = 38;
  public int JJTOVERWORLD = 39;
  public int JJTBEDROCK = 40;
  public int JJTTIPOINTEIRO = 41;
  public int JJTTIPOFLUTUANTE = 42;
  public int JJTTIPOTEXTO = 43;
  public int JJTTIPOBINARIO = 44;
  public int JJTIF = 45;
  public int JJTTHEN = 46;
  public int JJTELSE = 47;
  public int JJTTRUE = 48;
  public int JJTFALSE = 49;
  public int JJTPRINTF = 50;
  public int JJTCONTINUE = 51;
  public int JJTAND = 52;
  public int JJTOR = 53;
  public int JJTNOT = 54;
  public int JJTABRIRELSE = 55;
  public int JJTFECHARELSE = 56;
  public int JJTABRIRIF = 57;
  public int JJTFECHARIF = 58;
  public int JJTWHILE = 59;
  public int JJTABRIRWHILE = 60;
  public int JJTFECHARWHILE = 61;
  public int JJTBREAK = 62;
  public int JJTFOR = 63;
  public int JJTABRIRFOR = 64;
  public int JJTFECHARFOR = 65;
  public int JJTSOMA = 66;
  public int JJTSUBTRACAO = 67;
  public int JJTMULTIPLICACAO = 68;
  public int JJTDIVISAO = 69;
  public int JJTMAIOR = 70;
  public int JJTMENOR = 71;
  public int JJTMENOR_IGUAL = 72;
  public int JJTMAIOR_IGUAL = 73;
  public int JJTDIFERENTE = 74;
  public int JJTIGUAL = 75;
  public int JJTDECIMAL = 76;
  public int JJTDIGITO = 77;
  public int JJTID = 78;
  public int JJTLETRA = 79;
  public int JJTPONTOVIRGULA = 80;
  public int JJTVIRGULA = 81;
  public int JJTSTRING = 82;
  public int JJTPARENTES_ESQUERDA = 83;
  public int JJTPARENTES_DIREITA = 84;
  public int JJTDELIMITAR_VARCHAR = 85;


  public String[] jjtNodeName = {
    "main",
    "bloco",
    "comando",
    "whileLoop",
    "blocoWhile",
    "breakStmt",
    "continueStmt",
    "forLoop",
    "blocoFor",
    "forInitOpt",
    "forCondOpt",
    "forUpdateOpt",
    "forInit",
    "atribuicaoFor",
    "ifStmt",
    "elseClause",
    "blocoIf",
    "blocoElse",
    "atribuicao",
    "printStmt",
    "expressao",
    "exprOr",
    "exprOrLinha",
    "exprAnd",
    "exprAndLinha",
    "exprRel",
    "exprRelLinha",
    "exprAditiva",
    "exprAditivaLinha",
    "exprMultiplicativa",
    "exprMultiplicativaLinha",
    "exprUnaria",
    "exprPrimaria",
    "declaracaoVariavel",
    "listaDeclaracoes",
    "declaracaoUnica",
    "tipoDado",
    "tipoCondicao",
    "CREATEWORLD",
    "OVERWORLD",
    "BEDROCK",
    "TIPOINTEIRO",
    "TIPOFLUTUANTE",
    "TIPOTEXTO",
    "TIPOBINARIO",
    "IF",
    "THEN",
    "ELSE",
    "TRUE",
    "FALSE",
    "PRINTF",
    "CONTINUE",
    "AND",
    "OR",
    "NOT",
    "ABRIRELSE",
    "FECHARELSE",
    "ABRIRIF",
    "FECHARIF",
    "WHILE",
    "ABRIRWHILE",
    "FECHARWHILE",
    "BREAK",
    "FOR",
    "ABRIRFOR",
    "FECHARFOR",
    "SOMA",
    "SUBTRACAO",
    "MULTIPLICACAO",
    "DIVISAO",
    "MAIOR",
    "MENOR",
    "MENOR_IGUAL",
    "MAIOR_IGUAL",
    "DIFERENTE",
    "IGUAL",
    "DECIMAL",
    "DIGITO",
    "ID",
    "LETRA",
    "PONTOVIRGULA",
    "VIRGULA",
    "STRING",
    "PARENTES_ESQUERDA",
    "PARENTES_DIREITA",
    "DELIMITAR_VARCHAR",
  };
}
/* JavaCC - OriginalChecksum=10b496caf6301e8dc20d51c974037f17 (do not edit this line) */
