/* Generated By:JavaCC: Do not edit this line. CompiladorAulaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorAulaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CRIARMUNDO = 5;
  /** RegularExpression Id. */
  int MUNDOABERTO = 6;
  /** RegularExpression Id. */
  int ROCHAMAE = 7;
  /** RegularExpression Id. */
  int TIPOINTEIRO = 8;
  /** RegularExpression Id. */
  int TIPOFLUTUANTE = 9;
  /** RegularExpression Id. */
  int TIPOTEXTO = 10;
  /** RegularExpression Id. */
  int TIPOGRAVETO = 11;
  /** RegularExpression Id. */
  int TIPODIAMANTE = 12;
  /** RegularExpression Id. */
  int TIPOBINARIO = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int SOMA = 17;
  /** RegularExpression Id. */
  int SUBTRACAO = 18;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 19;
  /** RegularExpression Id. */
  int DIVISAO = 20;
  /** RegularExpression Id. */
  int ATRIBUICAO = 21;
  /** RegularExpression Id. */
  int MAIOR = 22;
  /** RegularExpression Id. */
  int MENOR = 23;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 24;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 25;
  /** RegularExpression Id. */
  int DIFERENTE = 26;
  /** RegularExpression Id. */
  int IGUAL = 27;
  /** RegularExpression Id. */
  int DECIMAL = 28;
  /** RegularExpression Id. */
  int DIGITO = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int LETRA = 31;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int PARENTES_ESQUERDA = 34;
  /** RegularExpression Id. */
  int PARENTES_DIREITA = 35;
  /** RegularExpression Id. */
  int DELIMITAR_VARCHAR = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"criarmundo\"",
    "\"mundoaberto\"",
    "\"rochamae\"",
    "\"pedra\"",
    "\"agua\"",
    "\"placa\"",
    "\"graveto\"",
    "\"blocoDiamante\"",
    "\"redstone\"",
    "\"if\"",
    "\"build\"",
    "\"drop\"",
    "\"combine\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<-\"",
    "\"stronger\"",
    "\"weaker\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"=\"",
    "<DECIMAL>",
    "<DIGITO>",
    "<ID>",
    "<LETRA>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
  };

}
