/* CompiladorAulaTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. CompiladorAulaTokenManager.java */

/** Token Manager. */
public class CompiladorAulaTokenManager implements CompiladorAulaConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xc3ffffffe0L) != 0L)
         {
            jjmatchedKind = 46;
            return 7;
         }
         if ((active0 & 0x20000000000000L) != 0L)
            return 8;
         return -1;
      case 1:
         if ((active0 & 0xc3ffefffe0L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 1;
            return 7;
         }
         if ((active0 & 0x100000L) != 0L)
            return 7;
         return -1;
      case 2:
         if ((active0 & 0xc3ffefffe0L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 2;
            return 7;
         }
         return -1;
      case 3:
         if ((active0 & 0xc3dfedfde0L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 3;
            return 7;
         }
         if ((active0 & 0x20020200L) != 0L)
            return 7;
         return -1;
      case 4:
         if ((active0 & 0xc3dfedd8e0L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
            return 7;
         }
         if ((active0 & 0x2500L) != 0L)
            return 7;
         return -1;
      case 5:
         if ((active0 & 0x43dfed98e0L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 5;
            return 7;
         }
         if ((active0 & 0x8000004000L) != 0L)
            return 7;
         return -1;
      case 6:
         if ((active0 & 0x41dfed9860L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 6;
            return 7;
         }
         if ((active0 & 0x200000080L) != 0L)
            return 7;
         return -1;
      case 7:
         if ((active0 & 0x1dfed9060L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 7;
            return 7;
         }
         if ((active0 & 0x4000000800L) != 0L)
            return 7;
         return -1;
      case 8:
         if ((active0 & 0x1dfe59020L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 8;
            return 7;
         }
         if ((active0 & 0x80040L) != 0L)
            return 7;
         return -1;
      case 9:
         if ((active0 & 0x1dfe18020L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 9;
            return 7;
         }
         if ((active0 & 0x41000L) != 0L)
            return 7;
         return -1;
      case 10:
         if ((active0 & 0x1dfe18000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 10;
            return 7;
         }
         if ((active0 & 0x20L) != 0L)
            return 7;
         return -1;
      case 11:
         if ((active0 & 0x1dfe10000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 11;
            return 7;
         }
         if ((active0 & 0x8000L) != 0L)
            return 7;
         return -1;
      case 12:
         if ((active0 & 0x1d7e00000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 12;
            return 7;
         }
         if ((active0 & 0x8010000L) != 0L)
            return 7;
         return -1;
      case 13:
         if ((active0 & 0x1d7e00000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 13;
            return 7;
         }
         return -1;
      case 14:
         if ((active0 & 0x1d7800000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 14;
            return 7;
         }
         if ((active0 & 0x600000L) != 0L)
            return 7;
         return -1;
      case 15:
         if ((active0 & 0x180000000L) != 0L)
            return 7;
         if ((active0 & 0x57800000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 15;
            return 7;
         }
         return -1;
      case 16:
         if ((active0 & 0x3000000L) != 0L)
            return 7;
         if ((active0 & 0x54800000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 16;
            return 7;
         }
         return -1;
      case 17:
         if ((active0 & 0x54800000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 17;
            return 7;
         }
         return -1;
      case 18:
         if ((active0 & 0x54000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 18;
            return 7;
         }
         if ((active0 & 0x800000L) != 0L)
            return 7;
         return -1;
      case 19:
         if ((active0 & 0x54000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 19;
            return 7;
         }
         return -1;
      case 20:
         if ((active0 & 0x54000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 20;
            return 7;
         }
         return -1;
      case 21:
         if ((active0 & 0x50000000L) != 0L)
            return 7;
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 21;
            return 7;
         }
         return -1;
      case 22:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 22;
            return 7;
         }
         return -1;
      case 23:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 23;
            return 7;
         }
         return -1;
      case 24:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 24;
            return 7;
         }
         return -1;
      case 25:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 25;
            return 7;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 39:
         return jjStartNfaWithStates_0(0, 53, 8);
      case 40:
         return jjStopAtPos(0, 51);
      case 41:
         return jjStopAtPos(0, 52);
      case 42:
         return jjStopAtPos(0, 35);
      case 44:
         return jjStopAtPos(0, 49);
      case 45:
         return jjStopAtPos(0, 34);
      case 47:
         return jjStopAtPos(0, 36);
      case 59:
         return jjStopAtPos(0, 48);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x52000000000L);
      case 61:
         return jjStopAtPos(0, 43);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x400200L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2080L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x200020020L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x18000000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x3000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x40040000L);
      case 106:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 107:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x100040L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x180000500L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x80800L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x218000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 37);
         break;
      case 61:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 40);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         break;
      case 62:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1b800000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000080980L);
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x20001000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x38021c000L);
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(1, 20, 7);
         return jjMoveStringLiteralDfa2_0(active0, 0x20L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa3_0(active0, 0x4800000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000020400L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x218000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x980L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x60L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x203000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x440000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x4198000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x4020L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x204000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x3080000L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x218000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
      case 108:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x42000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x18000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x404001c0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 7);
         return jjMoveStringLiteralDfa4_0(active0, 0x180800000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x18000000L);
      case 97:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 7);
         else if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 7);
         return jjMoveStringLiteralDfa5_0(active0, 0x180a58000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 100:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 7);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000080L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x80820L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x40218000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x440000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x18000000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x81000L);
      case 107:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 7);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x180000000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000840L);
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 7);
         break;
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x180000000L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x458000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x43080000L);
      case 101:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 7);
         return jjMoveStringLiteralDfa7_0(active0, 0x4018000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 107:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 7, 7);
         break;
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 119:
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0x18800000L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x4400000L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x180040000L);
      case 101:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 7);
         return jjMoveStringLiteralDfa8_0(active0, 0x3000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x40L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x40080020L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 114:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 38, 7);
         break;
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000L);
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0x47000000L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x410000L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000L);
      case 100:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 6, 7);
         break;
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 102:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x180040000L);
      case 114:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(8, 19, 7);
         return jjMoveStringLiteralDfa9_0(active0, 0x20L);
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 51:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(9, 12, 7);
         break;
      case 95:
         return jjMoveStringLiteralDfa10_0(active0, 0x180400000L);
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x10800000L);
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000L);
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x8200000L);
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x20L);
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(9, 18, 7);
         return jjMoveStringLiteralDfa10_0(active0, 0x2008000L);
      case 118:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x84010000L);
      case 100:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(10, 5, 7);
         break;
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000L);
      case 103:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x110000000L);
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x9200000L);
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000000L);
      case 97:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(11, 15, 7);
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000L);
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0x810000L);
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x181400000L);
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000L);
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0xa000000L);
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000000L);
      case 97:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(12, 16, 7);
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0xa00000L);
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000L);
      case 111:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(12, 27, 7);
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000L);
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x180000000L);
      case 118:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x4000000L);
      case 100:
         return jjMoveStringLiteralDfa14_0(active0, 0x10200000L);
      case 104:
         return jjMoveStringLiteralDfa14_0(active0, 0x180000000L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      case 109:
         return jjMoveStringLiteralDfa14_0(active0, 0x40000000L);
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x1c00000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000000L);
      case 97:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(14, 21, 7);
         return jjMoveStringLiteralDfa15_0(active0, 0x800000L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(14, 22, 7);
         return jjMoveStringLiteralDfa15_0(active0, 0x190000000L);
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x1000000L);
      case 115:
         return jjMoveStringLiteralDfa15_0(active0, 0x4000000L);
      case 118:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa16_0(active0, 0x10000000L);
      case 97:
         return jjMoveStringLiteralDfa16_0(active0, 0x6000000L);
      case 100:
         return jjMoveStringLiteralDfa16_0(active0, 0x800000L);
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x40000000L);
      case 114:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(15, 31, 7);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(15, 32, 7);
         break;
      case 118:
         return jjMoveStringLiteralDfa16_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa17_0(active0, 0x4000000L);
      case 97:
         return jjMoveStringLiteralDfa17_0(active0, 0x10000000L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(16, 24, 7);
         break;
      case 108:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(16, 25, 7);
         break;
      case 117:
         return jjMoveStringLiteralDfa17_0(active0, 0x800000L);
      case 120:
         return jjMoveStringLiteralDfa17_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa18_0(active0, 0x4000000L);
      case 99:
         return jjMoveStringLiteralDfa18_0(active0, 0x10000000L);
      case 114:
         return jjMoveStringLiteralDfa18_0(active0, 0x800000L);
      case 116:
         return jjMoveStringLiteralDfa18_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(18, 23, 7);
         break;
      case 114:
         return jjMoveStringLiteralDfa19_0(active0, 0x40000000L);
      case 117:
         return jjMoveStringLiteralDfa19_0(active0, 0x14000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa20_0(active0, 0x10000000L);
      case 101:
         return jjMoveStringLiteralDfa20_0(active0, 0x40000000L);
      case 116:
         return jjMoveStringLiteralDfa20_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa21_0(active0, 0x10000000L);
      case 109:
         return jjMoveStringLiteralDfa21_0(active0, 0x40000000L);
      case 111:
         return jjMoveStringLiteralDfa21_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0);
      return 21;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(21, 30, 7);
         break;
      case 109:
         return jjMoveStringLiteralDfa22_0(active0, 0x4000000L);
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(21, 28, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(20, active0);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0);
      return 22;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa23_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(21, active0);
}
static private int jjMoveStringLiteralDfa23_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(21, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0);
      return 23;
   }
   switch(curChar)
   {
      case 116:
         return jjMoveStringLiteralDfa24_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(22, active0);
}
static private int jjMoveStringLiteralDfa24_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(22, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0);
      return 24;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa25_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(23, active0);
}
static private int jjMoveStringLiteralDfa25_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(23, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, active0);
      return 25;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa26_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(24, active0);
}
static private int jjMoveStringLiteralDfa26_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(24, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(25, active0);
      return 26;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(26, 26, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(25, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 8;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  else if (curChar == 39)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 44)
                        kind = 44;
                     { jjCheckNAddTwoStates(3, 4); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 1:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 39 && kind > 50)
                     kind = 50;
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 4:
                  if (curChar == 46)
                     { jjCheckNAdd(5); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  { jjCheckNAdd(5); }
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjstateSet[jjnewStateCnt++] = 7;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
               case 1:
                  { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(7); }
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(7); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 8 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\143\162\145\141\164\145\167\157\162\154\144", 
"\157\166\145\162\167\157\162\154\144", "\142\145\144\162\157\143\153", "\160\145\144\162\141", "\141\147\165\141", 
"\160\154\141\143\141", "\162\145\144\163\164\157\156\145", "\166\151\156\151\143\151\165\163\61\63", 
"\142\165\151\154\144", "\155\157\156\141\162\153", 
"\164\157\143\150\141\137\141\143\145\163\163\141", "\164\157\143\150\141\137\141\160\141\147\141\144\141", "\143\150\141\164", 
"\151\163\157\154\141\141\141\144\157\163", "\162\145\160\145\164\151\144\157\162", "\157\162", 
"\164\157\143\150\141\137\151\156\166\145\162\164\151\144\141", "\141\143\157\162\144\141\141\141\141\137\147\145\156\164\145", 
"\152\141\137\164\141\155\157\137\156\141\137\144\151\164\141\144\165\162\141", "\147\141\155\145\155\157\144\145\137\143\162\145\141\164\151\166\145", 
"\147\141\155\145\155\157\144\145\137\163\165\162\166\151\166\141\154", 
"\145\155\137\142\165\163\143\141\137\144\141\137\143\141\163\141\137\141\165\164\157\155\141\164\151\143\141", "\146\141\162\155\137\144\145\137\146\145\162\162\157", 
"\146\141\162\155\137\144\145\137\143\141\156\141\137\144\145\137\141\143\165\143\141\162", "\153\151\154\154", 
"\151\156\164\162\157\137\144\157\137\166\145\156\157\155\137\145\170\164\162\145\155\145", "\160\157\162\164\141\154\137\144\157\137\141\145\164\150\145\162", 
"\160\157\162\164\141\154\137\144\157\137\156\145\164\150\145\162", "\143\157\155\142\151\156\145", "\55", "\52", "\57", "\74\55", 
"\163\164\162\157\156\147\145\162", "\167\145\141\153\145\162", "\74\75", "\76\75", "\74\76", "\75", null, null, 
null, null, "\73", "\54", null, "\50", "\51", "\47", };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {0
};

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

    /** Constructor. */
    public CompiladorAulaTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public CompiladorAulaTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 8; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x3fffffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[8];
    static private final int[] jjstateSet = new int[2 * 8];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
